### ISSUE TITLE
关于 bExistPlayerAfterLogout

### ISSUE THREAD

**Issue by Bluefissure** [knva/PalWorld_server_config#1]
有经过测试是全部登出后自动关闭服务器的设定吗？

看名字应该是玩家登出后仍存在的意思？

**Comment by knva** [comment]
参照https://docs.google.com/spreadsheets/u/0/d/e/2PACX-1vS6HbRTq53vrPTi0Yp1XPR9dzWI_0bvVcpjudvooXapY81IZO77pp4O24wA9h_NLFFXue-XewIJWn0J/pubhtml?pli=1
但是经过我测试并没有什么卵用。

**Comment by Bluefissure** [comment]
> 参照https://docs.google.com/spreadsheets/u/0/d/e/2PACX-1vS6HbRTq53vrPTi0Yp1XPR9dzWI_0bvVcpjudvooXapY81IZO77pp4O24wA9h_NLFFXue-XewIJWn0J/pubhtml?pli=1 但是经过我测试并没有什么卵用。

我感觉他也是把 `Exist` 看成 `Exit` 了
